# This is a template for your secrets.toml file
# In Streamlit Cloud, you should set these values in the app settings
# rather than committing this file to your repository

# Backend connection settings
BACKEND_URL = "https://your-backend-url.com/api/predict"

# You can add other secrets here as needed 